In [8]:
import os

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [1]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
import pandas as pd

movies = pd.read_csv("netflix_cleaned.csv")

In [9]:
movies = movies.drop('duration', axis=1)
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867,10192 A bored and domesticated Shrek pacts wit...
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630,"27205 Cobb, a skilled thief who commits corpor..."
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t..."
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732,"38757 Feisty teenager Rapunzel, who has long a..."
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471,10191 As the son of a Viking leader on the cus...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12448,616846,Movie,Psykopat,"Matthew Hart, Renaldo Samsara","Arifin Putra, Cornelio Sunny, Nana Mirdad, Mar...","Indonesia, United Kingdom, United States of Am...",2025-02-06,2025,3.000,"Drama, Thriller, Mystery, Horror",id,A famous illusionist challenges four participa...,4.955,1,3.000,0,0,616846 A famous illusionist challenges four pa...
12449,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,Horror,en,A young girl plays a violent game after her si...,4.953,0,0.000,0,0,1424086 A young girl plays a violent game afte...
12450,1214052,Movie,To a Land Unknown,Mahdi Fleifel,"Mahmood Bakri, Aram Sabbah, Angeliki Papoulia,...","Germany, Saudi Arabia, Qatar, France, Greece, ...",2025-02-14,2025,6.500,"Drama, Thriller, Crime",ar,The stakes couldn't be higher for displaced Pa...,4.946,2,6.500,0,0,1214052 The stakes couldn't be higher for disp...
12451,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0,0,1271724 Poignant stories about men and women w...
12452,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0,0,1405742 After a debt-collector finds a portal ...

In [10]:
movies["tagged_description"].to_csv("tagged_description.txt", sep=" ", index=False, header=False)

In [11]:
raw_documents = TextLoader("tagged_description.txt", encoding="latin-1").load()
text_splitter = CharacterTextSplitter(chunk_size = 500, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 604, which is longer than the specified 500
Created a chunk of size 537, which is longer than the specified 500
Created a chunk of size 554, which is longer than the specified 500
Created a chunk of size 627, which is longer than the specified 500
Created a chunk of size 524, which is longer than the specified 500
Created a chunk of size 542, which is longer than the specified 500
Created a chunk of size 542, which is longer than the specified 500
Created a chunk of size 583, which is longer than the specified 500
Created a chunk of size 531, which is longer than the specified 500
Created a chunk of size 542, which is longer than the specified 500
Created a chunk of size 590, which is longer than the specified 500
Created a chunk of size 547, which is longer than the specified 500
Created a chunk of size 702, which is longer than the specified 500
Created a chunk of size 703, which is longer than the specified 500
Created a chunk of size 608, which is longer than the specified 500
Created a chunk of size 557, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 800, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 859, which is longer than the specified 500
Created a chunk of size 640, which is longer than the specified 500
Created a chunk of size 621, which is longer than the specified 500
Created a chunk of size 593, which is longer than the specified 500
Created a chunk of size 728, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 692, which is longer than the specified 500
Created a chunk of size 532, which is longer than the specified 500
Created a chunk of size 526, which is longer than the specified 500
Created a chunk of size 580, which is longer than the specified 500
Created a chunk of size 605, which is longer than the specified 500
Created a chunk of size 583, which is longer than the specified 500
Created a chunk of size 617, which is longer than the specified 500
Created a chunk of size 662, which is longer than the specified 500
Created a chunk of size 531, which is longer than the specified 500
Created a chunk of size 627, which is longer than the specified 500
Created a chunk of size 661, which is longer than the specified 500
Created a chunk of size 581, which is longer than the specified 500
Created a chunk of size 720, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 551, which is longer than the specified 500
Created a chunk of size 643, which is longer than the specified 500
Created a chunk of size 614, which is longer than the specified 500
Created a chunk of size 706, which is longer than the specified 500
Created a chunk of size 503, which is longer than the specified 500
Created a chunk of size 551, which is longer than the specified 500
Created a chunk of size 780, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 573, which is longer than the specified 500
Created a chunk of size 997, which is longer than the specified 500
Created a chunk of size 537, which is longer than the specified 500
Created a chunk of size 805, which is longer than the specified 500
Created a chunk of size 670, which is longer than the specified 500
Created a chunk of size 992, which is longer than the specified 500
Created a chunk of size 780, which is longer than the specified 500
Created a chunk of size 832, which is longer than the specified 500
Created a chunk of size 562, which is longer than the specified 500
Created a chunk of size 633, which is longer than the specified 500
Created a chunk of size 539, which is longer than the specified 500
Created a chunk of size 528, which is longer than the specified 500
Created a chunk of size 612, which is longer than the specified 500
Created a chunk of size 851, which is longer than the specified 500
Created a chunk of size 516, which is longer than the specified 500
Created a chunk of size 711, which is longer than the specified 500
Created a chunk of size 532, which is longer than the specified 500
Created a chunk of size 740, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 517, which is longer than the specified 500
Created a chunk of size 647, which is longer than the specified 500
Created a chunk of size 859, which is longer than the specified 500
Created a chunk of size 714, which is longer than the specified 500
Created a chunk of size 685, which is longer than the specified 500
Created a chunk of size 510, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 609, which is longer than the specified 500
Created a chunk of size 532, which is longer than the specified 500
Created a chunk of size 544, which is longer than the specified 500
Created a chunk of size 581, which is longer than the specified 500
Created a chunk of size 949, which is longer than the specified 500
Created a chunk of size 737, which is longer than the specified 500
Created a chunk of size 741, which is longer than the specified 500
Created a chunk of size 768, which is longer than the specified 500
Created a chunk of size 516, which is longer than the specified 500
Created a chunk of size 501, which is longer than the specified 500
Created a chunk of size 739, which is longer than the specified 500
Created a chunk of size 917, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 552, which is longer than the specified 500
Created a chunk of size 502, which is longer than the specified 500
Created a chunk of size 739, which is longer than the specified 500
Created a chunk of size 645, which is longer than the specified 500
Created a chunk of size 768, which is longer than the specified 500
Created a chunk of size 656, which is longer than the specified 500
Created a chunk of size 656, which is longer than the specified 500
Created a chunk of size 538, which is longer than the specified 500
Created a chunk of size 586, which is longer than the specified 500
Created a chunk of size 552, which is longer than the specified 500
Created a chunk of size 635, which is longer than the specified 500
Created a chunk of size 515, which is longer than the specified 500
Created a chunk of size 585, which is longer than the specified 500
Created a chunk of size 678, which is longer than the specified 500
Created a chunk of size 549, which is longer than the specified 500
Created a chunk of size 666, which is longer than the specified 500
Created a chunk of size 740, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 640, which is longer than the specified 500
Created a chunk of size 643, which is longer than the specified 500
Created a chunk of size 515, which is longer than the specified 500
Created a chunk of size 881, which is longer than the specified 500
Created a chunk of size 744, which is longer than the specified 500
Created a chunk of size 714, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 760, which is longer than the specified 500
Created a chunk of size 589, which is longer than the specified 500
Created a chunk of size 717, which is longer than the specified 500
Created a chunk of size 562, which is longer than the specified 500
Created a chunk of size 536, which is longer than the specified 500
Created a chunk of size 650, which is longer than the specified 500
Created a chunk of size 584, which is longer than the specified 500
Created a chunk of size 550, which is longer than the specified 500
Created a chunk of size 609, which is longer than the specified 500
Created a chunk of size 578, which is longer than the specified 500
Created a chunk of size 739, which is longer than the specified 500
Created a chunk of size 784, which is longer than the specified 500
Created a chunk of size 569, which is longer than the specified 500
Created a chunk of size 517, which is longer than the specified 500
Created a chunk of size 638, which is longer than the specified 500
Created a chunk of size 924, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 541, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 576, which is longer than the specified 500
Created a chunk of size 715, which is longer than the specified 500
Created a chunk of size 653, which is longer than the specified 500
Created a chunk of size 562, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 1006, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 515, which is longer than the specified 500
Created a chunk of size 692, which is longer than the specified 500
Created a chunk of size 654, which is longer than the specified 500
Created a chunk of size 609, which is longer than the specified 500
Created a chunk of size 746, which is longer than the specified 500
Created a chunk of size 930, which is longer than the specified 500
Created a chunk of size 848, which is longer than the specified 500
Created a chunk of size 703, which is longer than the specified 500
Created a chunk of size 589, which is longer than the specified 500
Created a chunk of size 828, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 808, which is longer than the specified 500
Created a chunk of size 967, which is longer than the specified 500
Created a chunk of size 796, which is longer than the specified 500
Created a chunk of size 1007, which is longer than the specified 500
Created a chunk of size 647, which is longer than the specified 500
Created a chunk of size 531, which is longer than the specified 500
Created a chunk of size 639, which is longer than the specified 500
Created a chunk of size 581, which is longer than the specified 500
Created a chunk of size 561, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 504, which is longer than the specified 500
Created a chunk of size 538, which is longer than the specified 500
Created a chunk of size 667, which is longer than the specified 500
Created a chunk of size 620, which is longer than the specified 500
Created a chunk of size 642, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 574, which is longer than the specified 500
Created a chunk of size 724, which is longer than the specified 500
Created a chunk of size 529, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 711, which is longer than the specified 500
Created a chunk of size 506, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 546, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 510, which is longer than the specified 500
Created a chunk of size 630, which is longer than the specified 500
Created a chunk of size 631, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 725, which is longer than the specified 500
Created a chunk of size 836, which is longer than the specified 500
Created a chunk of size 541, which is longer than the specified 500
Created a chunk of size 597, which is longer than the specified 500
Created a chunk of size 893, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 645, which is longer than the specified 500
Created a chunk of size 704, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 540, which is longer than the specified 500
Created a chunk of size 516, which is longer than the specified 500
Created a chunk of size 562, which is longer than the specified 500
Created a chunk of size 643, which is longer than the specified 500
Created a chunk of size 778, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 598, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 930, which is longer than the specified 500
Created a chunk of size 573, which is longer than the specified 500
Created a chunk of size 612, which is longer than the specified 500
Created a chunk of size 646, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 641, which is longer than the specified 500
Created a chunk of size 643, which is longer than the specified 500
Created a chunk of size 650, which is longer than the specified 500
Created a chunk of size 803, which is longer than the specified 500
Created a chunk of size 603, which is longer than the specified 500
Created a chunk of size 612, which is longer than the specified 500
Created a chunk of size 539, which is longer than the specified 500
Created a chunk of size 698, which is longer than the specified 500
Created a chunk of size 856, which is longer than the specified 500
Created a chunk of size 763, which is longer than the specified 500
Created a chunk of size 753, which is longer than the specified 500
Created a chunk of size 865, which is longer than the specified 500
Created a chunk of size 643, which is longer than the specified 500
Created a chunk of size 533, which is longer than the specified 500
Created a chunk of size 534, which is longer than the specified 500
Created a chunk of size 506, which is longer than the specified 500
Created a chunk of size 746, which is longer than the specified 500
Created a chunk of size 634, which is longer than the specified 500
Created a chunk of size 508, which is longer than the specified 500
Created a chunk of size 628, which is longer than the specified 500
Created a chunk of size 552, which is longer than the specified 500
Created a chunk of size 752, which is longer than the specified 500
Created a chunk of size 1001, which is longer than the specified 500
Created a chunk of size 546, which is longer than the specified 500
Created a chunk of size 591, which is longer than the specified 500
Created a chunk of size 548, which is longer than the specified 500
Created a chunk of size 542, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 878, which is longer than the specified 500
Created a chunk of size 504, which is longer than the specified 500
Created a chunk of size 501, which is longer than the specified 500
Created a chunk of size 896, which is longer than the specified 500
Created a chunk of size 613, which is longer than the specified 500
Created a chunk of size 566, which is longer than the specified 500
Created a chunk of size 507, which is longer than the specified 500
Created a chunk of size 623, which is longer than the specified 500
Created a chunk of size 512, which is longer than the specified 500
Created a chunk of size 993, which is longer than the specified 500
Created a chunk of size 525, which is longer than the specified 500
Created a chunk of size 619, which is longer than the specified 500
Created a chunk of size 650, which is longer than the specified 500
Created a chunk of size 656, which is longer than the specified 500
Created a chunk of size 509, which is longer than the specified 500
Created a chunk of size 790, which is longer than the specified 500
Created a chunk of size 509, which is longer than the specified 500
Created a chunk of size 630, which is longer than the specified 500
Created a chunk of size 699, which is longer than the specified 500
Created a chunk of size 505, which is longer than the specified 500
Created a chunk of size 799, which is longer than the specified 500
Created a chunk of size 636, which is longer than the specified 500
Created a chunk of size 552, which is longer than the specified 500
Created a chunk of size 619, which is longer than the specified 500
Created a chunk of size 736, which is longer than the specified 500
Created a chunk of size 745, which is longer than the specified 500
Created a chunk of size 597, which is longer than the specified 500
Created a chunk of size 834, which is longer than the specified 500
Created a chunk of size 517, which is longer than the specified 500
Created a chunk of size 530, which is longer than the specified 500
Created a chunk of size 717, which is longer than the specified 500
Created a chunk of size 662, which is longer than the specified 500
Created a chunk of size 646, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 566, which is longer than the specified 500
Created a chunk of size 528, which is longer than the specified 500
Created a chunk of size 584, which is longer than the specified 500
Created a chunk of size 745, which is longer than the specified 500
Created a chunk of size 751, which is longer than the specified 500
Created a chunk of size 822, which is longer than the specified 500
Created a chunk of size 805, which is longer than the specified 500
Created a chunk of size 591, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 909, which is longer than the specified 500
Created a chunk of size 508, which is longer than the specified 500
Created a chunk of size 630, which is longer than the specified 500
Created a chunk of size 771, which is longer than the specified 500
Created a chunk of size 905, which is longer than the specified 500
Created a chunk of size 949, which is longer than the specified 500
Created a chunk of size 531, which is longer than the specified 500
Created a chunk of size 511, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 579, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 997, which is longer than the specified 500
Created a chunk of size 913, which is longer than the specified 500
Created a chunk of size 789, which is longer than the specified 500
Created a chunk of size 685, which is longer than the specified 500
Created a chunk of size 703, which is longer than the specified 500
Created a chunk of size 524, which is longer than the specified 500
Created a chunk of size 646, which is longer than the specified 500
Created a chunk of size 738, which is longer than the specified 500

In [12]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"10192 A bored and domesticated Shrek pacts with deal-maker Rumpelstiltskin to get back to feeling like a real ogre again, but when he\'s duped and sent to a twisted version of Far Far Awayâ\x80\x94where Rumpelstiltskin is king, ogres are hunted, and he and Fiona have never metâ\x80\x94he sets out to restore his world and reclaim his true love."')

In [13]:
embeddings = OpenAIEmbeddings(openai_api_key="sk-proj-vqxFO67TR57HgvFLgd0oFU2r9V1G2S3Gx3RZFDH8FfrV3AgunfgE-5n9p1uxKi-wwjjKbWdLbhT3BlbkFJkgguRT4VTxO_Tqil8zoHqtX7rcFinVP93_JBh_GpFvtwDNsYZKB8yFKMw1OrYckubzKhPTA")

In [14]:
db_movies = Chroma.from_documents(documents,embedding=embeddings)

In [15]:
query = "A kids movie"
docs = db_movies.similarity_search(query, k=10)
docs

[Document(id='c4f47c79-359e-46a9-b81e-3ab6f2b7b064', metadata={'source': 'tagged_description.txt'}, page_content='"347035 Four children dream of escaping the tedium of a summer holiday with their mother. When finally given permission to camp on their own on an island in the middle of a vast lake, they are overjoyed. But when they get there they discover they may not be aloneâ\x80¦ The battle for ownership of a lonely island teaches them the skills of survival, the value of friendship and the importance of holding your nerve."'),
 Document(id='e86b36d6-4a70-43ba-a26e-577c9b1a5e2e', metadata={'source': 'tagged_description.txt'}, page_content='"73723 A 12-year-old boy searches for the one thing that will enable him to win the affection of the girl of his dreams. To find it he must discover the story of the Lorax, the grumpy yet charming creature who fights to protect his world."'),
 Document(id='a4a5d9e8-2b0e-4a3a-b4f9-b8c317a0ddf7', metadata={'source': 'tagged_description.txt'}, page_content='"394117 The story of a precocious six year-old and her ragtag group of friends whose summer break is filled with childhood wonder, possibility and a sense of adventure while the adults around them struggle with hard times."'),
 Document(id='d5e4bf0b-1798-4ff4-894a-6c682506c8f7', metadata={'source': 'tagged_description.txt'}, page_content='"61591 Five children save the life of a dog-like alien while at a self-run summer camp. He attempts to reward them by taking them to an alien colony on the Moon. Events take a turn for the worse when his report on that attack that injured him causes passage from the Moon to the Earth to be banned, and children are stranded in space. The children need to find a way back home before camp ends and their parents discover that they are missing. They also have to avoid the poachers that injured their alien friend, and now seem to be stalking them all."'),
 Document(id='ddcba260-7e81-4a6b-b993-39bd15e7b1cb', metadata={'source': 'tagged_description.txt'}, page_content='"309809 Based on the best-seller book \'The Little Prince\', the movie tells the story of a little girl that lives with resignation in a world where efficiency and work are the only dogmas. Everything will change when accidentally she discovers her neighbor that will tell her about the story of the Little Prince that he once met."'),
 Document(id='24e9045a-6d4f-4b1a-b425-5b26c8f4eeac', metadata={'source': 'tagged_description.txt'}, page_content='"152581 Animated film based on the wonderful children\'s picture book written by Julia Donaldson and illustrated by Axel Scheffler.  The story of a kind witch who invites a surprising collection of animals to join her on her broom, much to the frustration of her cat. The gang ultimately saves the witch from a fearsome dragon, and in gratitude she rewards them with a magnificent new broom which has room for everyone.  A magical tale about friendship and family from Magic Light Pictures, the producers of the hugely successful The Gruffalo and The Gruffalo\'s Child."'),
 Document(id='1b35c8bd-0e4d-4e2a-a05f-c129e9261cf6', metadata={'source': 'tagged_description.txt'}, page_content='"367961 A fairytale about a grand life journey of a 10-year old boy Savva devoted to help his Mom and fellow village people to break free from the vicious hyenas."'),
 Document(id='d4e9432a-fac4-4e04-b3d6-a7a21c319ca6', metadata={'source': 'tagged_description.txt'}, page_content='"223706 Suffering because of his father\'s departure to the big city, a boy leaves his village and discovers a fantastic world dominated by bug-engines and strange beings. An unusual animation with various artistic techniques that portrays the issues of the modern world through the eyes of a child."'),
 Document(id='c73c8d83-ccef-483f-b50b-815ad5e6c0c4', metadata={'source': 'tagged_description.txt'}, page_content='"924763 A fun camping trip turns into a desperate fight for survival after two kids witness a horrific event in the wild. They have to endure the elements and wildlife and they must also find a way to reach civilization before it\'s too late."'),
 Document(id='c584025c-b8ae-4dd8-b39e-0cb4ed885c86', metadata={'source': 'tagged_description.txt'}, page_content='"928480 When a mysterious force begins to disrupt their big summer fun, Noah and his friends team up with a retired police detective to embark on a monstrous adventure to save their island."')]

In [16]:
movies[movies["show_id"] == int(docs[0].page_content.split()[0].strip('"'))]

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description
5217,347035,Movie,Swallows and Amazons,Philippa Lowthorpe,"Dane Hughes, Orla Hill, Teddie-Rose Malleson-A...",United Kingdom,2016-08-19,2016,6.3,"Adventure, Family",en,Four children dream of escaping the tedium of ...,9.506,89,6.3,0,0,347035 Four children dream of escaping the ted...

In [19]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int=10,
) -> pd.DataFrame:
    recs = db_movies.similarity_search(query,k=50)

    movies_list = []

    for i in range(0, len(recs)):
        movies_list+= [int(recs[i].page_content.split()[0].strip('"'))]

    return movies[movies["show_id"].isin(movies_list)].head(top_k)

In [20]:
retrieve_semantic_recommendations("A harry potter movie")

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,budget,revenue,tagged_description
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868,"12444 Harry, Ron and Hermione walk away from t..."
48,7978,Movie,The Wolfman,Joe Johnston,"Benicio del Toro, Anthony Hopkins, Emily Blunt...",United States of America,2010-02-10,2010,5.900,"Horror, Thriller",en,"Lawrence Talbot, an American man on a visit to...",33.064,2014,5.900,150000000,140700000,"7978 Lawrence Talbot, an American man on a vis..."
798,70448,Movie,All About Evil,Joshua Grannell,"Natasha Lyonne, Thomas Dekker, Cassandra Peter...",United States of America,2010-05-01,2010,6.000,"Horror, Comedy",en,A mousy librarian inherits her father's belove...,4.150,52,6.000,0,0,70448 A mousy librarian inherits her father's ...
840,12445,Movie,Harry Potter and the Deathly Hallows: Part 2,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, R...","United Kingdom, United States of America",2011-07-12,2011,8.089,"Fantasy, Adventure",en,"Harry, Ron and Hermione continue their quest t...",115.252,20842,8.089,125000000,1341511219,"12445 Harry, Ron and Hermione continue their q..."
1046,483898,Movie,50 Greatest Harry Potter Moments,NaN,"Robbie Coltrane, Daniel Radcliffe, Emma Watson...",United Kingdom,2011-07-27,2011,7.500,Documentary,en,To mark the release two weeks ago of the eight...,13.084,130,7.500,0,0,483898 To mark the release two weeks ago of th...
1226,80530,Movie,Magic Beyond Words: The J.K. Rowling Story,Paul A. Kaufman,"Poppy Montgomery, Emily Holmes, Antonio Cupo, ...",United States of America,2011-07-18,2011,6.900,Drama,en,A look at J.K. Rowling from her humble beginni...,8.499,208,6.900,0,0,80530 A look at J.K. Rowling from her humble b...
1265,74842,Movie,Legend of the Millennium Dragon,Hirotsugu Kawasaki,"Satomi Ishihara, Kentaro Ito, Yasuyuki Kase, S...",Japan,2011-04-29,2011,5.800,"Animation, Adventure, Fantasy",ja,A spectacular journey of an unwilling young he...,7.865,50,5.800,0,0,74842 A spectacular journey of an unwilling yo...
1639,49051,Movie,The Hobbit: An Unexpected Journey,Peter Jackson,"Martin Freeman, Ian McKellen, Richard Armitage...","New Zealand, United States of America",2012-12-12,2012,7.357,"Adventure, Fantasy, Action",en,"Bilbo Baggins, a hobbit enjoying his quiet lif...",88.877,18623,7.357,250000000,1021103568,"49051 Bilbo Baggins, a hobbit enjoying his qui..."
1662,76726,Movie,Chronicle,Josh Trank,"Dane DeHaan, Alex Russell, Michael B. Jordan, ...",United States of America,2012-02-01,2012,6.800,"Science Fiction, Drama, Thriller",en,Three high school students make an incredible ...,46.737,5348,6.800,15000000,145000000,76726 Three high school students make an incre...
1844,152581,Movie,Room on the Broom,"Jan Lachauer, Max Lang","Gillian Anderson, Timothy Spall, Sally Hawkins...",United Kingdom,2012-12-25,2012,6.500,"Family, Animation",en,Animated film based on the wonderful children'...,13.748,100,6.500,0,0,152581 Animated film based on the wonderful ch...

In [22]:
movies["genres"].value_counts()

genres
Drama                                       1046
Comedy                                       579
Drama, Romance                               377
Documentary                                  365
Comedy, Drama                                296
                                            ...
Drama, Science Fiction, Fantasy, Romance       1
Animation, Music                               1
Comedy, Mystery, Drama                         1
Drama, History, Fantasy                        1
Thriller, Romance, Horror                      1
Name: count, Length: 2436, dtype: int64

In [23]:
movies["genres"].value_counts().reset_index().query("count > 50")

                       genres  count
0                       Drama   1046
1                      Comedy    579
2              Drama, Romance    377
3                 Documentary    365
4               Comedy, Drama    296
5                      Horror    288
6            Horror, Thriller    277
7             Comedy, Romance    188
8              Romance, Drama    183
9                     Romance    176
10            Drama, Thriller    166
11              Drama, Comedy    162
12           Action, Thriller    138
13             Drama, History    134
14            Romance, Comedy    126
15                   Thriller    124
16     Comedy, Drama, Romance    107
17    Action, Crime, Thriller     89
18            Thriller, Drama     88
19  Horror, Mystery, Thriller     85
20                     Action     77
21           Thriller, Horror     68
22     Crime, Drama, Thriller     67
23            Horror, Mystery     62
24              Action, Drama     59
25             Action, Comedy     57
26     Drama, Comedy, Romance     55
27          Animation, Family     54
28               Crime, Drama     54
29             Comedy, Horror     52
30             Horror, Comedy     52
31    Action, Thriller, Crime     51